account.default-amount=500
account.transfer-commission=5
db.connection-url=${DB_CONNECTION_URL}
db.username=${DB_USERNAME}
db.password=${DB_PASSWORD}
hibernate.show_sql=true
hibernate.format_sql=true
hibernate.highlight_sql=true
hibernate.hbm2ddl.auto=update